/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/staging/clouds/clouds.glb  --types --keepnames --shadows --transform --simplify
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cloudZero: THREE.Mesh
    cloudOne: THREE.Mesh
    cloudTwo: THREE.Mesh
    CloudThree: THREE.Mesh
    cloudFour: THREE.Mesh
  }
  materials: {
    aiStandardSurface1SG: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/clouds-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="cloudZero" castShadow receiveShadow geometry={nodes.cloudZero.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="cloudOne" castShadow receiveShadow geometry={nodes.cloudOne.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="cloudTwo" castShadow receiveShadow geometry={nodes.cloudTwo.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="CloudThree" castShadow receiveShadow geometry={nodes.CloudThree.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="cloudFour" castShadow receiveShadow geometry={nodes.cloudFour.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/clouds-transformed.glb')
