/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/staging/cloudTwo/cloudTwo.glb  --types --keepnames --shadows --transform --simplify
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cloudTwo: THREE.Mesh
  }
  materials: {
    aiStandardSurface1SG: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cloudTwo-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="cloudTwo" castShadow receiveShadow geometry={nodes.cloudTwo.geometry} material={materials.aiStandardSurface1SG} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cloudTwo-transformed.glb')
