/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/staging/cloudOne/cloudOne.glb  --types --keepnames --shadows --transform --simplify
*/

import type { Mesh, MeshStandardMaterial } from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    cloudOne: Mesh;
  };
  materials: {
    aiStandardSurface1SG: MeshStandardMaterial;
  };
};

const FILE_URL = 'https://dqeczc7c9n9n1.cloudfront.net/models/cloudOne-1681881812/cloudOne.glb';

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(FILE_URL) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="cloudOne"
        castShadow
        receiveShadow
        geometry={nodes.cloudOne.geometry}
        material={materials.aiStandardSurface1SG}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload(FILE_URL);
